#include "../script_component.hpp"

#define IDD_RSCDISPLAYCURATOR 312
#define IDC_RSCDISPLAYCURATOR_CREATE_MODULES 280
#define IDC_RSCDISPLAYCURATOR_MOUSEAREA 53
#define IDC_RSCDISPLAYCURATOR_MAINMAP 50
